### ISSUE TITLE
在.NET Framework 4.5.2中下载依赖包失败

### ISSUE THREAD

**Issue by liaoliaoda** [huaweicloud/huaweicloud-sdk-net-v3#3]
在.NET Framework 4.5.2中使用Install-Package HuaweiCloud.SDK.IoTDA -Version 3.0.25-beta下载安装包失败，在.NET Framework 4.6.1中能正常下载安装

**Comment by mawenbo-huawei** [comment]
华为云 .Net SDK 适用于.NET Framework 4.6及以上版本
