### ISSUE TITLE
通用文字OCR bug

### ISSUE THREAD

**Issue by Jackcu** [huaweicloud/huaweicloud-sdk-net-v3#51]
`  public HuaweiOCR(Auth auth) {

        var ak = auth.ak;
        var sk = auth.sk;
        var endpoint = auth.endpoint;
        var projectId = auth.projectId;

        this.auth = auth;

        Credentials auth1 = new BasicCredentials(ak,sk,projectId);

        var config = HttpConfig.GetDefaultConfig();
        config.IgnoreSslVerification = true;
        config.Timeout = 120;

        _client = OcrAsyncClient.NewBuilder()
           .WithCredential(auth1)
           .WithRegion(OcrRegion.ValueOf(endpoint))
           .WithLogging(LogLevel.Error)
           .WithHttpConfig(config)
           .WithHttpHandler(new HttpHandler().AddResponseHandler(responseHandler))
           .Build();

    }

    private void responseHandler(HttpResponseMessage message,ILogger logger) {

        var resStr = message.Content.ReadAsStringAsync().Result;

        //fix:华为bug
        //获取到 "direction": 359.94864328702823
        //这个值无法转换成int,但是华为定义了int
        var directionValue = resStr.regFirstMatchGroupValue(@"""direction""\:\ ?(?<d>[.\d]+)[,\ ]*?$","d","");
        if(!string.IsNullOrWhiteSpace(directionValue)) {
            resStr = resStr.Replace(directionValue,((int)double.Parse(directionValue)).ToString());
        }

        message.Content = new StringContent(resStr,Encoding.UTF8,"application/json");
        
    }`

**Comment by mawenbo-huawei** [comment]
已收到您的反馈，会尽快进行修复。

**Comment by mawenbo-huawei** [comment]
问题已在`3.0.94`版本修复
