### ISSUE TITLE
IoTDA使用listDeviceMessages查询设备消息提示“发生一个或多个错误“

### ISSUE THREAD

**Issue by Jycjmf** [huaweicloud/huaweicloud-sdk-net-v3#6]
我已经使用了IoTDAClient.NewBuilder()建立了iotdaClient，但是当我尝试调用 ”listDeviceMessages(iotdaClient);"时提示“发生一个或多个错误。”
![image](https://user-images.githubusercontent.com/30173232/117528231-b1d74e00-b003-11eb-96dd-5b1048fc1bac.png)

```
  private static void listDeviceMessages(IoTDAClient client)
        {
            ListDeviceMessagesRequest req = new ListDeviceMessagesRequest
            {
                DeviceId = "6093c42aa6467502c0466fda_Demo"
            };
            try
            {
                var resp = client.ListDeviceMessages(req);
                Console.WriteLine(resp);
            }
            catch (RequestTimeoutException requestTimeoutException)
            {
                Console.WriteLine(requestTimeoutException.ErrorMessage);
            }
            catch (ServiceResponseException clientRequestException)
            {
                Console.WriteLine(clientRequestException.HttpStatusCode);
                Console.WriteLine(clientRequestException.ErrorCode);
                Console.WriteLine(clientRequestException.ErrorMsg);
            }
            catch (ConnectionException connectionException)
            {
                Console.WriteLine(connectionException.ErrorMessage);
            }
        }
```
使用同一个客户端下发设备消息则是正常的。我尝试在API Explorer页面中执行同样的查询，返回的数值是正常的，请问下这个是说明原因啊？非常感谢！
![image](https://user-images.githubusercontent.com/30173232/117528203-90766200-b003-11eb-8946-8ae5f48f21d9.png)

**Comment by wuchen-huawei** [comment]
你好，我这边本地调试 `ListDeviceMessages` 接口是可以正常返回的，由于网络限制无法上传图片，如果您的问题一直存在，可以在华为云上新建工单。这样我们的研发同事可以通过外部会议快速定位问题

**Comment by Jycjmf** [comment]
> 你好，我这边本地调试 `ListDeviceMessages` 接口是可以正常返回的，由于网络限制无法上传图片，如果您的问题一直存在，可以在华为云上新建工单。这样我们的研发同事可以通过外部会议快速定位问题

@wuchen-huawei 刚刚下载源代码debug了一下，发现异常出现在“ this._sdkHttpClient.DoHttpRequest(message).Result;”，内容是“无法发送具有此谓词类型的内容正文。”
![image](https://user-images.githubusercontent.com/30173232/117536086-b6176180-b02b-11eb-80c6-c43c803ffaf0.png)
![image](https://user-images.githubusercontent.com/30173232/117536087-b7e12500-b02b-11eb-92d9-e1f40c2d7423.png)
![image](https://user-images.githubusercontent.com/30173232/117536088-b9aae880-b02b-11eb-8dc4-e3eccae13f66.png)

**Comment by wuchen-huawei** [comment]
我用的代码就是按照你上面说的那个代码写的，改了一下 DeviceId 的值。我这边不能直接上传截图，所以推荐您这边通过华为云工单的外部会议来定位问题。或者您这边提供一下使用的版本，我是用的最新版本的代码测试的。

**Comment by wuchen-huawei** [comment]
你好，上面没有向您确认框架是否是 .NET Framework。如果是使用的.NET Framework，在 [3.0.48](https://github.com/huaweicloud/huaweicloud-sdk-net-v3/releases/tag/v3.0.48) 版本中兼容当前问题，具体使用方式是在初始化 `IoTDAClient` 时增加如下配置：

``` csharp
var config = HttpConfig.GetDefaultConfig();
// 增加下面这行
config.IgnoreBodyForGetRequest = true;
var auth = new BasicCredentials(ak, sk, projectId);
var iotdaClient = IoTDAClient.NewBuilder()
    .WithCredential(auth)
    .WithEndPoint(endpoint)
    .WithHttpConfig(config)
    .Build();
```

如果使用上还有问题，可继续提交Issue或者在华为云上提交工单。
