### ISSUE TITLE
Enterprise Project Management Service

### ISSUE THREAD

**Issue by SyukurCode** [huaweicloud/huaweicloud-sdk-net-v3#62]
i got this error when execute my code why any my wrong?

![image](https://user-images.githubusercontent.com/67965783/208462567-57608cf4-31e8-491c-ab0d-3cf6c3a8f8ec.png)

**Comment by mawenbo-huawei** [comment]
EPS is a global service, use `GlobalCredentials` intead of `BasicCredentials`
