### ISSUE TITLE
Replace string concatenations with StringBuilder

### ISSUE THREAD

**Issue by suleymanoz** [huaweicloud/huaweicloud-sdk-net-v3#63]
In huaweicloud-sdk-net-v3/Core/Signer/Signer.cs at the ConstructCanonicalRequest method, string concatenation should be replaced with StringBuilder.

        protected string ConstructCanonicalRequest(HttpRequest request)
        {
            var builder = new StringBuilder();
            builder.Append(ProcessRequestMethod(request));
            builder.Append('\n');
            builder.Append(ProcessCanonicalUri(request));
            builder.Append('\n');
            builder.Append(ProcessCanonicalQueryString(request));
            builder.Append('\n');
            builder.Append(CanonicalHeaders(request));
            builder.Append('\n');
            builder.Append(Join(";", ProcessSignedHeaders(request)));
            builder.Append('\n');
            builder.Append(ProcessRequestPayload(request));
            return builder.ToString();
        }

Current code is not performant and possibly spoils the stack trace for a situation that we encounter.

![image](https://github.com/huaweicloud/huaweicloud-sdk-net-v3/assets/34645335/320a926f-280d-4f48-a465-1c01bbd33945)

**Comment by mawenbo-huawei** [comment]
Thank you for your feedback, I'm looking at this

**Comment by mawenbo-huawei** [comment]
This issue will be fixed in the next version.
