### ISSUE TITLE
HttpRequest signing must be done for invariant language.

### ISSUE THREAD

**Issue by suleymanoz** [huaweicloud/huaweicloud-sdk-net-v3#64]
Signer.ProcessSignedHeaders must use invariant language. Current version uses ToLower() method:

![image](https://github.com/huaweicloud/huaweicloud-sdk-net-v3/assets/34645335/5e6f6a44-a0db-4d4d-9b5e-ce0990d4eaa6)

This causes a problem in Turkish region (same for al Turkic languages).
![image](https://github.com/huaweicloud/huaweicloud-sdk-net-v3/assets/34645335/a9ae32c8-4ab2-4c64-b747-e2a0b43d3670)

In Turkic language "I".ToLower() is "ı" not "i".

ToLowerInvariant() method must be used:
![image](https://github.com/huaweicloud/huaweicloud-sdk-net-v3/assets/34645335/dd46d756-3f92-4c64-8e97-91e70674f296)

Please fix this. This is urgent.

**Comment by zoupengli** [comment]
Hello @suleymanoz , thank you for discovering this issue. This will be fixed on the next release version.

**Comment by suleymanoz** [comment]
When will be the next release?

**Comment by zoupengli** [comment]
this Thursday

**Comment by suleymanoz** [comment]
We need a workaround until Thursday.

**Comment by suleymanoz** [comment]
@zoupengli please provide a workaround for this issue, until it is resolved.

**Comment by suleymanoz** [comment]
Please, say something.

**Comment by zoupengli** [comment]
You can try something like this.

**Comment by suleymanoz** [comment]
We have tried this, but causes side effects, at other parts for our application.

**Comment by mawenbo-huawei** [comment]
try this:
```csharp
// Get the current culture
CultureInfo currentCulture = CultureInfo.CurrentCulture;

// switch to US culture
CultureInfo usCulture = new CultureInfo("en-US");
Thread.CurrentThread.CurrentCulture = usCulture;
Thread.CurrentThread.CurrentUICulture = usCulture;

// invoke huawei SDK

// reset culture
Thread.CurrentThread.CurrentCulture = currentCulture;
Thread.CurrentThread.CurrentUICulture = currentCulture;
```

**Comment by suleymanoz** [comment]
Thank you.

**Comment by mawenbo-huawei** [comment]
Hi, `ToLowerInvariant()` is used in v3.1.72
