### ISSUE TITLE
请问机器翻译使用哪个API啊?

### ISSUE THREAD

**Issue by adxpcc** [huaweicloud/huaweicloud-sdk-net-v3#65]
请问机器翻译使用哪个API啊?

**Comment by mawenbo-huawei** [comment]
咨询API问题请通过华为云控制台提交工单

**Comment by adxpcc** [comment]
> 咨询API问题请通过华为云控制台提交工单

你好,我的意思是 机器翻译 使用你们这个sdk里的那个方法啊?

**Comment by mawenbo-huawei** [comment]
参考API Explorer，https://console.huaweicloud.com/apiexplorer/#/openapi/NLP/sdk?api=RunFileTranslation
