### ISSUE TITLE
创建客户端需要做类似HttpClient单例处理嘛？

### ISSUE THREAD

**Issue by HmgsLJ** [huaweicloud/huaweicloud-sdk-net-v3#7]

**Comment by he1a2s0** [comment]
19天了，这个问题你应该已经解决了，我也遇到了，给后来人省点时间吧： 
不需要也不应该做单例处理。各个Client在Build()的时候会初始化 SdkHttpClient 类实例，SdkHttpClient 在构造函数中使用 HttpClientFactory.CreateClient 创建真正的 HttpClient。
所以 XXXClient 不应该是 Singleton

**Comment by mawenbo-huawei** [comment]
感谢您的回答，如您在使用上还有问题，请提交issue或者在华为云控制台上提交工单。
