### ISSUE TITLE
CES custom metric returns 400 error

### ISSUE THREAD

**Issue by sbcdemos** [huaweicloud/huaweicloud-sdk-net-v3#8]
I've tried to play with CES client and it works when doing "read" queries. But when I've tried to create custom metric - it returns 400 Bad request error.
All the authorization parameters are correct (it shows some data) and this action is really works from NodeJS code. But I need to send metrics from .NET CORE 3.1 program and cannot find working way to do this.

**Comment by mawenbo-huawei** [comment]
Any error code or error message in response? Do you use the same request parameters in both code?

**Comment by sbcdemos** [comment]
When I've tried to use old SDK version (4.0.2 with a bit different file structure) system returns with CES.0014 error. In this SDK we have no way to catch WebException and read the actual response unfortunatey (a good idea by the way!!).But absolutely identical request from NodeJS code (I've even put two requests in a line to compare - no difference) works pretty well.

**Comment by mawenbo-huawei** [comment]
CES.0014, it means that some content in message body is not correct. You could provide the request body and RequestId(important!), send to hwcloudsdk@huawei.com.
